create type categories_name as enum ('MISC', 'CREDIT_CARD', 'RECURRING_SPENDS', 'SAVING');

alter type categories_name owner to postgres;

create table categories
(
    id   bigint generated by default as identity
        primary key,
    date timestamp(6),
    name categories_name default 'MISC'::categories_name not null
);

alter table categories
    owner to postgres;

create table transactions
(
    id          bigint generated by default as identity
        primary key,
    amount      numeric(38, 2),
    date        timestamp(6),
    description varchar(255),
    recurring   boolean not null,
    category_id bigint  not null
        constraint fksqqi7sneo04kast0o138h19mv
            references categories
);

alter table transactions
    owner to postgres;

create table recurring_transactions
(
    id             bigint generated by default as identity
        primary key,
    active         boolean not null,
    created_date   timestamp(6),
    paid_date      timestamp(6),
    transaction_id bigint
        constraint uk7j9em5564hsex2ugwmvu3uaby
            unique
        constraint fkfqjfg0lv4aacrmt4p8teiqakd
            references transactions
);

alter table recurring_transactions
    owner to postgres;