create type categories_name as enum ('MISC', 'CREDIT_CARD', 'RECURRING_SPENDS', 'SAVING');

alter type categories_name owner to postgres;

create table categories
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint ukt8o6pivur7nn124jehx7cygw5
            unique
        constraint categories_name_check
            check ((name)::text = ANY
                   ((ARRAY ['OTHER'::character varying, 'CREDIT_CARD'::character varying, 'RECREATION'::character varying, 'SAVING'::character varying, 'UNIVERSITY'::character varying])::text[]))
);

alter table categories
    owner to postgres;

create table transactions
(
    id          bigint generated by default as identity
        primary key,
    amount      numeric(38, 2) not null,
    date        timestamp(6)   not null,
    description varchar(255)   not null,
    recurring   boolean        not null,
    category_id bigint         not null
        constraint fksqqi7sneo04kast0o138h19mv
            references categories
);

alter table transactions
    owner to postgres;


INSERT INTO categories VALUES (1, 'OTHER'), (2, 'CREDIT_CARD'), (3, 'RECREATION'), (4, 'SAVING'), (5, 'UNIVERSITY');